name: Checks
on:
  pull_request:
  merge_group:
  push:
    branches:
      - main

permissions: read-all

jobs:
  fmt:
    name: Formatting
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v3
      - uses: dprint/check@2f1cf31537886c3bfb05591c031f7744e48ba8a1 # v2.2

  lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@61fe2df320078202e33d7d5ad347e7dcfa0e8f31 # v1.1.0
        with:
          deno-version: v1.33.3
      - run: deno lint

  spellcheck:
    name: Spelling
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v3
      - uses: streetsidesoftware/cspell-action@c5eae96241f654d2437c16bdfad146ff33a025cc # v2.7.0

  star:
    name: Star
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@61fe2df320078202e33d7d5ad347e7dcfa0e8f31 # v1.1.0
        with:
          deno-version: v1.33.3
      - run: deno task star

  test:
    name: Tests
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@61fe2df320078202e33d7d5ad347e7dcfa0e8f31 # v1.1.0
        with:
          deno-version: v1.33.3
      - run: deno task test
